### ISSUE TITLE
Withdraw all

### ISSUE THREAD

**Issue by darosior** [lvaccaro/lamp#26]
As with `fundchannel`, it would be great to be able to `withdraw [address] all` from the dialog without having to use the console

**Comment by vincenzopalazzo** [comment]
Hi @darosior,

I'm working on this right now, if you want to test this solution you can found the code on my [master branch](https://github.com/vincenzopalazzo/lamp) :)

You can use the function scan QR or also you can past the address from clipboard. In addition, I think that this solution is not possible from the menu bar because the input text accept only number, I will change the type of input also to permit to intern all :+1:

**Comment by darosior** [comment]
Hi, thank you for working on this. I think the addition of a `all` switch which would deactivate the existing input (and send the `all` string to `lightningd` via RPC instead of a number) would be more appropriate than changing the type of the existing input: what do you think ?

**Comment by vincenzopalazzo** [comment]
I think that your solution is more responsible for the mine :) I agree with you.

**Comment by lvaccaro** [comment]
This should be solved in #22
