### ISSUE TITLE
Package already downloaded. Uncompressing... never ends

### ISSUE THREAD

**Issue by jsarenik** [lvaccaro/lamp#80]
After an upgrade to latest master (ce98119) the lamp is not starting properly.
It seems to notice `lightningd` is old so it downloads the new archive and then tries to uncompress it.
Without success. It does not start. The lamp blinks like if it was doing something. No log of what is happening (or at least I do not know how to get it).

**Comment by vincenzopalazzo** [comment]
@jsarenik I will see to reproduce this problem, thanks for reporting it

**Comment by lvaccaro** [comment]
If you have a previous clightning_ndk version installed, it is better to remove the binary folder from settings before fetching a new one. This is not supposed to happen in every clightning_ndk updates, but it could happens in the last release because latest clightning_ndk update the inner path of binaries inside the archive.

**Comment by jsarenik** [comment]
@lvaccaro What does "remove the binary folder from settings" mean exactly? What steps should I do? My Android phone is rooted.

**Comment by lvaccaro** [comment]
Lamp has some app settings accessible from the top right menu -> settings. At the end of the list you have some combination to remove :
- data folder (with your lightning secret data),
- binary folder (maybe you want remove in order to download new binary version)
- log folder (clear space and old logs)

Otherwise, you can clean the data folder from phone settings -> app -> lamp, but you remove also the entire wallet.

I am really sorry for this issue, I hope the upgrading mechanism as implemented now should works good for the next v0.9.2 updates (without manually remove the binary folder).

**Comment by jsarenik** [comment]
@lvaccaro Thank you! I used the `Erase binary dir` option in `Settings`, restarted LAMP and everything works now. Thanks!
